sudo: required
dist: trusty
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
language: scala

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh


jdk:
- oraclejdk8
stages:
- test
jobs:
  include:
  - stage: test
    script: sbt test

matrix:
  include:
    # GraalVM
    - env: JDK='GraalVM 19'
      install: . ./install-jdk.sh --verbose --url "https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-linux-amd64-19.2.1.tar.gz"

script:
  - gu install native-image
  - travis_wait sbt graalvm-native-image:packageBin
