sudo: required
dist: trusty
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
language: scala
jdk:
- oraclejdk8
stages:
- test
jobs:
  include:
  - stage: test
    script: sbt test
